### PR TITLE
new gdrive test file

### PR DESCRIPTION
**Pull request by lludlow**
updated with working 1gb gdrive test file

### CODE REVIEW

**Comment by sayem314** [comment]
We only use/allow 100MB test file at max!

**Comment by lludlow** [comment]
I knew that, I should have had more coffee... updated to 100mb

**Comment by sayem314** [comment]
Why do you even need to update 100MB files? Our current link is valid and working and it is hosted on Gsuite plan.

**Comment by sayem314** [comment]
Here is a screenshot from last minute test!

**Comment by lludlow** [comment]
interesting, I ran this today several times and got no results. I made the assumption the file was no longer available 

> tested just now and the same thing

screen shot 2018-10-22 at 2 14 44 pm

**Comment by sayem314** [comment]
Will take a look tomorrow with other VM’s.

**Comment by lludlow** [comment]
This is from another machine running in azure, I've ran this on a server with heztner, ovh, and our local DC here in Detroit
screen shot 2018-10-22 at 2 18 29 pm

**Pull request merged**
